-- RECOVERY SCRIPT: Re-import existing stories from Storage to DB
-- Path structure: stories/2026/01/[slug]/main.mp3

-- Base URL
-- https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/

INSERT INTO stories (id, title, slug, description, category, duration, audio_url, cover_url, cover_landscape_url, cover_portrait_url, is_premium, is_published, is_loop)
VALUES 
    (gen_random_uuid(), 
     '432Hz Healing Resonance', 
     '432hz-healing-resonance',
     'Deep healing frequency meditation', 
     'meditation', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/432hz-healing-resonance/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/432hz-healing-resonance/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/432hz-healing-resonance/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/432hz-healing-resonance/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'Celestial Healing Resonance', 
     'celestial-healing-resonance',
     'Cosmic frequency healing experience', 
     'meditation', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/celestial-healing-resonance/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/celestial-healing-resonance/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/celestial-healing-resonance/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/celestial-healing-resonance/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'Cosmic Drift Sleep', 
     'cosmic-drift-sleep',
     'Drift through the cosmos into deep sleep', 
     'sleep', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/cosmic-drift-sleep/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/cosmic-drift-sleep/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/cosmic-drift-sleep/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/cosmic-drift-sleep/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'Nocturne in Glass', 
     'nocturne-in-glass',
     'A crystalline journey through the night', 
     'sleep', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/nocturne-in-glass/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/nocturne-in-glass/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/nocturne-in-glass/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/nocturne-in-glass/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'Temple Bell Meditation', 
     'temple-bell-meditation',
     'Peaceful temple bells for deep meditation', 
     'meditation', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/temple-bell-meditation/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/temple-bell-meditation/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/temple-bell-meditation/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/temple-bell-meditation/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'The Golden Harvest', 
     'the-golden-harvest',
     'A warm journey through autumn fields', 
     'nature', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-golden-harvest/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-golden-harvest/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-golden-harvest/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-golden-harvest/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'The Memory Quilt', 
     'the-memory-quilt',
     'Wrapped in comforting memories', 
     'sleep', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-memory-quilt/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-memory-quilt/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-memory-quilt/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-memory-quilt/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'The Velvet Descent', 
     'the-velvet-descent',
     'Sink into velvet darkness', 
     'sleep', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-velvet-descent/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-velvet-descent/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-velvet-descent/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/the-velvet-descent/cover_portrait.png',
     false, true, false),

    (gen_random_uuid(), 
     'Where Sand Holds Stars', 
     'where-sand-holds-stars',
     'Desert night under infinite stars', 
     'nature', 
     300, 
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/where-sand-holds-stars/main.mp3',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/where-sand-holds-stars/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/where-sand-holds-stars/cover_landscape.png',
     'https://xdotggbipohsrwvmqqlm.supabase.co/storage/v1/object/public/audio/stories/2026/01/where-sand-holds-stars/cover_portrait.png',
     false, true, false)
ON CONFLICT (slug) DO UPDATE SET
    audio_url = EXCLUDED.audio_url,
    cover_url = EXCLUDED.cover_url,
    cover_landscape_url = EXCLUDED.cover_landscape_url,
    cover_portrait_url = EXCLUDED.cover_portrait_url,
    is_published = true;
