-- Add 'is_loop' column to 'stories' table
-- This flag distinguishes standalone, reusable backing tracks from finished narratives.

ALTER TABLE stories 
ADD COLUMN is_loop BOOLEAN DEFAULT FALSE;

-- Optional: Create an index for faster lookup of loops during Factory generation
CREATE INDEX idx_stories_is_loop ON stories(is_loop);

-- Comment
COMMENT ON COLUMN stories.is_loop IS 'If TRUE, this story is a reusable backing track (component) generated by the Harvest Engine.';
