-- Add Audio Stems columns to stories table
-- Generated by Audio Factory Refactoring (V6 Unified)

ALTER TABLE public.stories 
ADD COLUMN IF NOT EXISTS voice_url text,
ADD COLUMN IF NOT EXISTS ambient_url text,
ADD COLUMN IF NOT EXISTS music_url text;

COMMENT ON COLUMN public.stories.voice_url IS 'URL for the isolated voice stem (silence + narration)';
COMMENT ON COLUMN public.stories.ambient_url IS 'URL for the isolated ambience loop';
COMMENT ON COLUMN public.stories.music_url IS 'URL for the isolated music loop';
